const Constants = {
    KEY_FIRST_RUN_EMAIL: "firstRunEmail",
    KEY_SHOULD_VERIFY_EMAIL: "shouldVerifyEmail",

    SETTING_ALPHA_UNDERSTANDS_RISKS: "ALPHA_UNDERSTANDS_RISKS",

    ACTION_FIRST_RUN_PAGE_CHANGED: "FIRST_RUN_PAGE_CHANGED",
};

export default Constants;
