const Constants = {
  KEY_FIRST_RUN_EMAIL: "firstRunEmail",
  KEY_SHOULD_VERIFY_EMAIL: "shouldVerifyEmail",
  KEY_EMAIL_VERIFY_PENDING: "emailVerifyPending",

  SETTING_ALPHA_UNDERSTANDS_RISKS: "alphaUnderstandRisks",

  ACTION_DELETE_COMPLETED_BLOBS: "DELETE_COMPLETED_BLOBS",
  ACTION_FIRST_RUN_PAGE_CHANGED: "FIRST_RUN_PAGE_CHANGED",

  ACTION_PUSH_DRAWER_STACK: "PUSH_DRAWER_STACK",
  ACTION_POP_DRAWER_STACK: "POP_DRAWER_STACK",

  PAGE_REWARDS: "rewards",
  PAGE_SETTINGS: "settings",
  PAGE_TRENDING: "trending",
  PAGE_WALLET: "wallet",

  DRAWER_ROUTE_DISCOVER: "Discover",
  DRAWER_ROUTE_TRENDING: "Trending",
  DRAWER_ROUTE_SUBSCRIPTIONS: "Subscriptions",
  DRAWER_ROUTE_MY_LBRY: "Downloads",
  DRAWER_ROUTE_REWARDS: "Rewards",
  DRAWER_ROUTE_WALLET: "Wallet",
  DRAWER_ROUTE_SETTINGS: "Settings",
  DRAWER_ROUTE_ABOUT: "About"
};

export default Constants;

export const DrawerRoutes = [
  Constants.DRAWER_ROUTE_DISCOVER,
  Constants.DRAWER_ROUTE_TRENDING,
  Constants.DRAWER_ROUTE_SUBSCRIPTIONS,
  Constants.DRAWER_ROUTE_MY_LBRY,
  Constants.DRAWER_ROUTE_REWARDS,
  Constants.DRAWER_ROUTE_WALLET,
  Constants.DRAWER_ROUTE_SETTINGS,
  Constants.DRAWER_ROUTE_ABOUT
];
