name: Publish APK

on:
  pull_request:
    branches: [test-deploy]
  push:
    branches: [test-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lbry/android-base:platform-28
    steps:
      - name: update git
        run: |
          apt install -y software-properties-common \
          apt update \
          add-apt-repository -y ppa:git-core/ppa \
          apt update \
          apt install -y git
      - name: checkout
        uses: actions/checkout@v3
      - name: aftercheckout
        run: |
          ls -al
          ls -al ..
          git --version
          pwd
      - name: hacky copy # docker image runs ~ as /root, but github actions uses ~=/github/home
        run: | 
          cp -r /root/.buildozer ~/.buildozer/
      - name: setup
        run: |
          echo "$PGP_PRIVATE_KEY" | gpg --batch --import
          echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list
          wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | apt-key add -
          apt-get -y update && apt-get -y install build-essential ca-certificates curl gpg-agent openjdk-8-jdk software-properties-common wget zipalign git-secret
          ls -al ..
          ls -al
          git rev-parse --is-inside-work-tree
          git secret reveal
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      # - name: Upload math result for job 1
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: homework
      #     path: math-homework.txt